### ISSUE TITLE
Image orientation issue with latest iOS 13.1.2 "Choose Image Size" feature

### ISSUE THREAD

**Issue by Alexn117** [disintegration/imaging#104] opened 2019-10-24 15:18 UTC
In iOS 13 when uploading an image you are prompted with the option to "Choose Image Size" on the selected image, to reduce the size of the original file for upload. This is optional, and you can upload the original large file if you wish.

When uploading the original image file, without using this feature, the image ends up being rotated properly by use of:

```
i, err := imaging.Decode(file, imaging.AutoOrientation(true))
if err != nil {
	return err
}
```

But, if you choose to resize the image to "Large", "Medium", or "Small" (using the "Choose Image Size" iOS feature), the uploaded image does not correct the orientation and remains rotated.

I believe iOS is doing something to the image uploaded with "Choose Image Size", that Disintegration is not taking account of. Perhaps there are additional computations and checks that need to be ran to properly adjust the orientation data of these images.

EDIT: test image below.
- without AutoOrientation set to true, if you upload the original it should display rotated in an HTML img tag.
- with AutoOrientation set to true, it will correct the rotation to confirm it works.
- but, if you resize the image with the new iOS feature and upload it, it will not correct the rotation. Display it in an HTML img tag to test.
- the image says "Orientation: 6 (Rotated 90° CCW)" on the TIFF tab of the inspector of the Preview app on macOS.
![IMG_3543 - no location](https://user-images.githubusercontent.com/29024614/67516712-1c69a880-f66f-11e9-904f-b72026868b84.jpg)

**Comment by disintegration** [comment] 2019-10-24 15:41
Thank you for the report!

Could you please attach an example image so I can reproduce the issue?

**Comment by Alexn117** [comment] 2019-10-24 19:09
Sure! See the original post above.

**Comment by disintegration** [comment] 2019-10-24 19:51
I've downloaded the test image and attached it to this comment with the “small size” setting using iOS 13.1.2:

![C16B14C4-047F-4E80-8905-5B0EB13E02A1](https://user-images.githubusercontent.com/2706839/67519777-3b3c5f00-f6b0-11e9-9c41-5d8ae262698a.jpeg)

**Comment by disintegration** [comment] 2019-10-24 20:41
The exif command-line utility reports "Right-top" orientation for the original image and "Top-left" for the small-size-uploaded one. It looks like the original orientation tag is lost for some reason when using this option.

I also tried to open these images using GIMP and the Gnome Image Viewer. Both of them display the first image correctly while the second one is displayed rotated.

**Comment by Alexn117** [comment] 2019-10-25 19:04
Yeah I'm seeing that iOS is changing the original orientation tag from the small-sized version. It is setting it to **Orientation: 1 (Normal)**. While the original image had **Orientation: 6 (Rotated 90° CCW)**. I'm seeing this data if you open each image with Preview on macOS > _Tools > Show Inspector > General_ tab. This website explains those numbers:

https://www.impulseadventure.com/photo/exif-orientation.html

I take it that since iOS changes the original orientation tag, there's no way of solving this? Have to report to Apple and wait for iOS to preserve the original orientation tag?

**Comment by disintegration** [comment] 2019-11-03 14:28
I've just conducted one more test just to ensure that github uploader isn't modying the image data. I've created a simple server with an upload form and used it to save the raw uploaded bytes to a file.

The result is the same as before: the uploaded image has the wrong orientation tag and the iOS software itself displays it rotated. Looks like it's an iOS issue.

**Comment by disintegration** [comment] 2019-11-16 20:48
I'm closing the issue, feel free to reopen if I missed something.

**Closed by disintegration** 2019-11-16 20:48 UTC

**Comment by Lelelo1** [comment] 2020-03-06 16:18
I also experienced this issue. I made a [cmd shift 4] screen shot for each original iPhone photo I intended to upload. They are rotated correctly.

**Comment by propagandaCreative** [comment] 2020-06-24 14:25
I'm experiencing this issue on a completely unrelated app I'm writing - anyone found any solutions to this?

**Comment by tomislavsantek** [comment] 2020-07-16 10:13
I'm afraid not. The orientation information is lost (apple device sets the orientation tag to 1 - normal), so there's no way to handle this right now :(

**Comment by SudoPlz** [comment] 2021-04-15 18:59
That's also our experience.. I think it's a bug on the Apple side..
