### ISSUE TITLE
TestResizeGolden,TestAdjustSaturationGolden fail on arm64,ppc64el,s390x

### ISSUE THREAD

**Issue by mwhudson** [disintegration/imaging#102] opened 2019-08-19 06:05 UTC
Like this:

```
=== RUN   TestAdjustSaturationGolden
--- FAIL: TestAdjustSaturationGolden (0.02s)
    adjust_test.go:238: resulting image differs from golden: out_saturation_m30.png
    adjust_test.go:238: resulting image differs from golden: out_saturation_p30.png
--- FAIL: TestResizeGolden (0.08s)
    resize_test.go:259: resulting image differs from golden: out_resize_linear.png
FAIL
FAIL	github.com/disintegration/imaging	0.173s
```

I hacked up TestResizeGolden to write the image to disk (on arm64 fwiw) and here it is: 
![foo](https://user-images.githubusercontent.com/672022/63242221-c5c8a280-c2aa-11e9-8ae1-b8396126b575.png) (I checked github hasn't recompressed it). Poking around I can see that 6 pixels around the edge of the image indeed differ (for example 8, 0 is 324a26 in one image and 324b26 in another).

This seems a bit bizarre to me, I don't see why this would differ between architectures. Some kind of difference in rounding, I assume.

**Comment by mwhudson** [comment] 2019-08-19 06:17
Oh and another thing, the test only fails (on arm64 at least) with Go 1.11 and newer which makes me suspicious... oh, I know what this will be: fused multiply-add, which go 1.11 emits on arm64 but 1.10 does not.

**Comment by disintegration** [comment] 2019-08-20 21:21
Thank you for the report!

Unfortunately I have zero experience with these architectures. I'm wondering If there's any way that I could reproduce this on amd64 linux laptop.

**Comment by mwhudson** [comment] 2019-08-20 21:48
I don't think there's going to be a way to reproduce this on your laptop. It probably supports FMA3 instructions but I don't think Go can generate them (I think there might be patches floating around to add this but well...). You can get limited free access to POWER or s390x systems though:

   https://developer.ibm.com/linuxone/
   http://openpower.ic.unicamp.br/minicloud/

(and you can get access to arm64 for fairly small amounts of money from packet.net or amazon)

For now I've uploaded a patch to Ubuntu to allow 1 bit of difference in the golden tests:

http://launchpadlibrarian.net/438030956/golang-github-disintegration-imaging_1.6.0+really1.6.0-1_1.6.0+really1.6.0-1ubuntu1.diff.gz

which I'm not super happy about but well.

I had a play at adding fma-suppressing casts (go will not emit fma for code of the form float64(a*b)+c) but I didn't manage to find the fma's that were causing the failures yet. I guess it's not completely certain that FMA is the culprit, but it seems pretty likely to me.

**Comment by mwhudson** [comment] 2019-08-20 22:22
Oh the other way you can reproduce locally of course is to use emulation:

(master)mwhudson@ringil:/opt/opensource/gopath/src/github.com/disintegration/imaging$ GOARCH=arm64 /snap/bin/go  test -c .
(master)mwhudson@ringil:/opt/opensource/gopath/src/github.com/disintegration/imaging$ qemu-aarch64-static ./imaging.test -test.run=TestResizeGolden
--- FAIL: TestResizeGolden (0.11s)
    resize_test.go:258: resulting image differs from golden: out_resize_linear.png
FAIL

Performance seems totally OK for this case, the test takes about 2s to run.

**Comment by mwhudson** [comment] 2019-08-20 22:52
So I can't leave things like this alone and found a set of casts to insert that make the testsuite pass on arm64 (under qemu as above): https://github.com/mwhudson/imaging/commit/231093e32e90b99d36d9224387142ae71a4367b4

It's of course extremely likely that other image manipulations will be affected by the presence or not of fma (for example, bcspline is full of them!) so I don't know that applying a patch like the above is doing anything really relevant. But at least it conforms my hypothesis that the differences are due to fma insertion, not some other change.

**Comment by disintegration** [comment] 2019-08-21 21:58
Thanks a lot! This is very helpful.

So it looks like there are two ways to deal with this issue:

1. Replace all instances of `a*b+c` with `float64(a*b)+c` in the code to disallow FMA, explicitly asking for intermediate rounding (or at least at those places that affect the failing tests). In this case we should probably also add some code comments to explain that the "redundant" floating-point type conversions are there on purpose. Cons of this method is that we potentially making the code less effective and less precise just for these tests to pass. 

2. Change the golden tests somehow, to allow some level of tolerance when comparing the output image to the golden image on non-amd64 architecture. All the golden images are generated on amd64, so we still can do exact comparisons when running tests on amd64 architecture. If some non-golden tests are affected we can modify the test inputs to avoid rounding issues. The Go compiler does not guarantee that the emitted binary code will produce the same (exact) results on all architectures, so maybe we should not require this in tests.

I'm not sure which of the above methods is the right one, but I'm leaning towards the second one. I'm planning to work on it as soon as time allows.

**Comment by mwhudson** [comment] 2019-08-22 04:17
Yeah. Option 1 would be very ugly in code and annoying to maintain I think (although one might be able to do it automatically with eg, maybe?). Unless you have a particular reason to want bit for bit identical output across architectures and Go releases, option 2 seems like the better option.

(still hate implicit insertion of fma)

**Comment by disintegration** [comment] 2019-08-24 11:37
It should be fixed now.

**Comment by disintegration** [comment] 2019-08-31 14:33
I'm closing the issue now. Feel free to reopen if needed.

**Closed by disintegration** 2019-08-31 14:33 UTC
