### ISSUE TITLE
It's not obvious that this package doesn't carry over EXIF data

### ISSUE THREAD

**Issue by artursapek** [disintegration/imaging#27] opened 2015-05-17 06:24 UTC
I've been using this package to rotate images as I migrate them from my laptop to a server, and I just went crazy trying to figure out why my EXIF data disappeared. It turns out that using this package caused that to happen. I am simply using `imaging.Open`, `imaging.Rotate180`, and `imaging.Save`. It appears that the transformation to an `image.NRGBA` makes that metadata disappear?

When automating simple tasks like rotation I think it makes sense that one would expect the image's metadata to remain. For example, ImageMagick's `convert` command line utility *does* maintain EXIF data when doing a simple rotate. I think this package should include a warning that that's not the case here.

**Comment by disintegration** [comment] 2015-05-17 07:29
This package is based on the standard Go `image` package, that don't handle the image metadata. You should use other packages for that. 

Duplicate of https://github.com/disintegration/imaging/issues/15

**Closed by disintegration** 2015-05-17 07:29 UTC
